### ISSUE TITLE
Why does TabBar need an ID?

### ISSUE THREAD

**Issue by heyarne** [rbb-data/starter#20]
I think it's not very intuitive to require the user to supply an ID. Maybe we can just generate a UUID if it's needed? Minor nitpick, but would make the interface cleaner.

**Comment by errnesto** [comment]
it is needed beacuse if we add multiple tab bars with the same id the selection will only work on the first one. (it uses radio buttons internally)

**Comment by heyarne** [comment]
Why would you want to add multiple tab bars with the same id?
> Maybe we can just generate a UUID if it's needed? Minor nitpick, but would make the interface cleaner.
Wouldn't that be a solution? It doesn't even have to be a UUID, maybe tab label + index would already be enough.

**Comment by errnesto** [comment]
> Why would you want to add multiple tab bars with the same id?
you would not!

It should have an id so you can use it in the <label for='id' />
And if you have multiple tab bars they all need a different id

So for me the simplest way was just to let the user provide one.
UUID also sound very nice to me.

I think i did not use the label because the user does not know it needs to be uniqe… idk
