### ISSUE TITLE
Add resizer script to starter

### ISSUE THREAD

**Issue by errnesto** [rbb-data/starter#39]
Add resizer script to starter by default.

When using maps we usually want a fixed height for components but most of the time we just want the iframe to have the height of the content.

So I think we shlould add the sizer script by default and add documentation on how to use this with an embed…
Maybe we can even automatically generate the embed code like we do in datawrapper switcher etc?

**Comment by heyarne** [comment]
While we're at it, a lazy-iframe polyfill might be useful as well. Adding `lazy` to the iframe-tag and accepting incomplete browser support may already help: https://caniuse.com/loading-lazy-attr

**Comment by sophiamersmann** [comment]
What's the resizer script Manu is referring to? I read about `iframeResizer.min.js` in our wiki, is that what he's referring to?

**Comment by heyarne** [comment]
Yup! It's about this script: https://github.com/davidjbradshaw/iframe-resizer

Its purpose is to automatically shrink iframes in the page where they are embedded, so that the iframe's dimensions match that of its content, so there are no scrollbars or extra whitespace no matter the device.

I was suggesting to group this with a `lazy` attribute on the embed code because this similarly is an improvement of how iframes are embedded by default.
